### ISSUE TITLE
Add Option for custom domains

### ISSUE THREAD

**Issue by rruprai** [minnur/language_suggestion#1]
Use Case:

- rather then using path prefix based translated page, we use custom domain for translation. 

Example domain:

- es.example.com/some/path
- de.example.com/some/path

Recommendations:

- On the admin screen add an option to allow for custom domains so that for English we can set redirect to www.example.com, but for Spanish we can set es.example.com
- Use JS to get the URI and append it to the domain based on language suggestion

I would like to offer support by helping code this up, but not sure if that is an option so created an issue to get the conversation going.

**Comment by minnur** [comment]
thanks for the suggestion. I will look into this. Probably I will create another field redirects.

**Comment by minnur** [comment]
I just added this feature. Please give it a try.

<img width="1659" alt="Screen Shot 2019-11-01 at 12 32 43 AM" src="https://user-images.githubusercontent.com/4031934/68009411-25461580-fc3f-11e9-9ac0-be2cf4fec839.png">
